// Factory shoot, Day 1: scripts S1-S10. Timings, dialogue and on-screen text come from the launch plan (pp. 32-42).
// Shot sizes, camera moves and frame art are SUGGESTIONS added for this guide.
import { C, frame, phone, hand, person, kiosk, timer, bubble, dust, filmSheet, blade, clothPad, sticker, note, arrow, curveArrow, circleMark, sparkle, crown, smiley, flash, floorPlan, sun } from './lib.mjs';

const skinA = C.skin[0], skinB = C.skin[1], skinC = C.skin[2];
const F = (o) => frame({ bg: 'factory', ...o });

export const SCRIPTS = [
  {
    id: 'S1', title: '“Bilkul Fit Hai”', kind: 'SKIT', len: 25, block: 'MACHINE BLOCK', tag: 'THE MACHINE',
    cast: 'Shopkeeper, customer', props: 'Dummy with a crooked, wrong-size film · kiosk · dust wipe · microfiber cloth',
    rule: 'Run the kiosk beat (11–21s) as one real take with a real timer in the corner. No speed-ramp.',
    plan: { kind: 'machine', cams: [{ x: 200, y: 116, ang: 0, label: 'A' }], actors: [{ x: 160, y: 78, label: 'SHOP', col: skinB }, { x: 240, y: 78, label: 'CUST', col: skinA }], lights: [{ x: 60, y: 90, label: 'KEY' }, { x: 340, y: 90, label: 'FILL' }] },
    beats: [
      { a: 0, b: 3, shot: 'CU → MCU', mv: 'pull', act: 'Crooked film, edge lifting. Shopkeeper, proud.', say: 'SHOP: “Bilkul fit hai, bhai.” (Fits perfectly, bro.)', text: 'Every shop. Every time.',
        art: () => F({ shot: 'CU', mv: 'pull', num: '1', body: phone(36, 52, 108, 214, { film: 'crooked', screen: 'glossy' }) + circleMark(132, 72, 15) + sticker(90, 292, 'EVERY SHOP. EVERY TIME.', { size: 11 }) }) },
      { a: 3, b: 7, shot: 'CU → MS', mv: 'pan', act: 'Customer tilts phone to camera; camera hole sits half over the lens.', say: 'CUST: “Bhai, camera ka hole kahan gaya?” SHOP: “Naya design hai.” (It’s the new design.)', text: '',
        art: () => F({ shot: 'CU', mv: 'pan', num: '2', body: person(62, 84, 1.15, { mood: 'worry', shirt: C.pink, longHair: true, skin: skinB }) + phone(84, 112, 76, 148, { rot: 12, film: 'crooked', screen: 'glossy' }) + circleMark(98, 128, 14) + hand(124, 262, 0.9, { rot: -8, skin: skinB }) }) },
      { a: 7, b: 11, shot: 'MACRO', mv: 'locked', act: 'Customer pokes the bubble; it slides around.', say: 'SHOP: “Do din mein khud chala jayega.” (It’ll leave by itself in two days.)', text: 'It did not leave.',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '3', body: phone(30, 62, 120, 236, { film: 'crooked', screen: 'glossy' }) + bubble(84, 168, 26) + hand(160, 214, 0.9, { rot: -90, skin: skinB }) + sticker(90, 296, 'IT DID NOT LEAVE.', { size: 12 }) }) },
      { a: 11, b: 21, shot: 'WS + INSERTS', mv: 'whip', act: 'Record-scratch cut to the kiosk: pick the model, blade cuts, wipe, peel, smooth. Real timer in the corner.', say: '', text: '',
        art: () => F({ shot: 'WS', mv: 'whip', num: '4', body: kiosk(40, 46, 100, 196) + timer(90, 272, '00:00:21', { size: 13 }) + clothPad(18, 262, 34, 22) + sparkle(160, 60, 10, C.ink) }) },
      { a: 21, b: 25, shot: 'MCU 2-shot', mv: 'locked', act: 'Customer holds the phone up, edge flush. Shopkeeper, tiny voice.', say: 'CUST: “Ab bolo.” (Now say it.) SHOP: “…bilkul fit hai.”', text: 'No more almost.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '5', body: person(56, 108, 1.25, { mood: 'smug', glasses: true, shirt: C.green, skin: skinA }) + phone(92, 62, 66, 126, { film: 'flush', screen: 'lit', rot: 6 }) + person(146, 232, 0.8, { mood: 'worry', mustache: true, shirt: '#fff', skin: skinC, bottom: 330 }) + sticker(90, 300, 'NO MORE ALMOST.', { size: 13 }) + sparkle(24, 70, 9, C.Y, C.ink) }) },
    ],
  },
  {
    id: 'S2', title: 'The Bubble Roommate', kind: 'VOICEOVER', len: 25, block: 'MACHINE BLOCK', tag: 'THE INSTALL',
    cast: 'Hands only + voiceover', props: 'Dummy with an old film and a bubble · dust wipe · microfiber · kiosk',
    rule: 'Record the voiceover separately in a quiet corner; shoot the hands silent. Keep rolling on every cut (shared footage with S1/S3/S9/S10).',
    plan: { kind: 'machine', cams: [{ x: 200, y: 116, ang: 0, label: 'A macro' }], actors: [{ x: 200, y: 62, label: 'HANDS', col: skinB }], lights: [{ x: 100, y: 100, label: 'KEY' }, { x: 300, y: 100, label: 'RAKE' }] },
    beats: [
      { a: 0, b: 3, shot: 'MACRO', mv: 'locked', act: 'Macro on the bubble.', say: 'VO: “This bubble has lived on my phone since 2023. Pays zero rent.”', text: '',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '1', body: phone(26, 52, 128, 240, { film: 'crooked', screen: 'glossy' }) + bubble(84, 172, 30) + note(90, 308, 'pays zero rent.', { size: 14 }) }) },
      { a: 3, b: 9, shot: 'CU', mv: 'locked', act: 'A thumb pushes it to the edge; it slides back to the centre.', say: 'VO: “I pushed it out. It came back. Like the cousin who ‘stays one night’.”', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '2', body: phone(30, 60, 120, 236, { film: 'crooked', screen: 'glossy' }) + bubble(70, 190, 18) + hand(146, 232, 0.85, { rot: -90, skin: skinB }) + curveArrow(110, 190, 130, 150, 84, 168, { w: 2.2 }) }) },
      { a: 9, b: 13, shot: 'CU slow-mo', mv: 'locked', act: 'Dramatic slow-mo peel of the old film.', say: 'VO: “So I did what had to be done.”', text: '',
        art: () => F({ shot: 'CU · 120 FPS', mv: 'locked', num: '3', body: phone(32, 80, 116, 220, { film: 'peel', screen: 'glossy' }) + hand(150, 112, 0.9, { rot: 140, skin: skinB }) + sticker(90, 300, 'SLOW-MO', { size: 12 }) }) },
      { a: 13, b: 21, shot: 'MCU → inserts', mv: 'whip', act: 'Dust wipe, microfiber, kiosk cut, new film goes on.', say: 'VO: “Clean house. New lease. Cut for this exact phone.”', text: '',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '4', body: kiosk(14, 54, 70, 138) + phone(98, 100, 58, 112, { film: 'flush', screen: 'lit' }) + clothPad(100, 232, 52, 28) + arrow([88, 130, 94, 130], { w: 2 }) }) },
      { a: 21, b: 25, shot: 'MACRO', mv: 'locked', act: 'A microfiber-wrapped thumb pushes the last tiny bubble off the edge.', say: 'VO: “Eviction complete.”', text: 'Bye bye, bubble.',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '5', body: phone(28, 64, 124, 232, { film: 'flush', screen: 'lit' }) + bubble(142, 200, 6) + hand(160, 236, 0.8, { rot: -80, skin: skinB }) + sticker(90, 302, 'BYE BYE, BUBBLE.', { size: 13 }) + sparkle(150, 46, 9, C.Y, C.ink) }) },
    ],
  },
  {
    id: 'S3', title: '60 Seconds, Go', kind: 'TEAM VS MACHINE', len: 30, block: 'MACHINE BLOCK', tag: 'THE MACHINE',
    cast: 'Three staffers + the machine', props: 'Kiosk · dummy · film · microfiber · dust wipe · stopwatch',
    rule: 'Real timer, no speed-ramp. The “under 60 seconds” line only goes out if the take really is.',
    plan: { kind: 'machine', cams: [{ x: 120, y: 116, ang: -10, label: 'A staff' }, { x: 290, y: 116, ang: 10, label: 'B kiosk' }], actors: [{ x: 90, y: 80, label: 'A', col: skinB }, { x: 150, y: 90, label: 'B', col: skinA }, { x: 215, y: 90, label: 'C', col: skinC }], lights: [{ x: 40, y: 70, label: 'KEY' }, { x: 360, y: 70, label: 'FILL' }] },
    beats: [
      { a: 0, b: 3, shot: 'MCU', mv: 'locked', act: 'A staffer starts the stopwatch.', say: 'STAFF A: “Team ko 60 second. Machine ko bhi.” (60 seconds for the team. Same for the machine.)', text: '60 seconds. Go.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '1', body: timer(90, 150, '60:00', { size: 28 }) + hand(90, 232, 1.1, { rot: 0, skin: skinB }) + sticker(90, 66, '60 SECONDS. GO.', { size: 15 }) }) },
      { a: 3, b: 12, shot: 'split screen', mv: 'locked', act: 'A tries to fold the microfiber into a swan. B tries “kacha papad, pakka papad” five times fast.', say: 'STAFF B: “Kacha papad, pakka papad…”', text: '',
        art: () => F({ shot: 'SPLIT', mv: 'locked', num: '2', body: `<rect x="0" y="158" width="180" height="162" fill="${C.Y2}"/><line x1="0" y1="160" x2="180" y2="160" stroke="${C.ink}" stroke-width="3"/>` + person(90, 86, 0.8, { mood: 'flat', shirt: C.purple, skin: skinB, bottom: 158 }) + `<path d="M118,128 q10,-26 22,-8 q-6,6 -2,12 q-12,6 -20,-4Z" fill="#fff" stroke="${C.ink}" stroke-width="2"/>` + person(90, 238, 0.8, { mood: 'open', shirt: C.green, skin: skinA, bottom: 320 }) }) },
      { a: 12, b: 20, shot: 'MS ↔ inserts', mv: 'whip', act: 'C can’t find the dust wipe he’s standing on. Cut between them and the machine: pick, cut, wipe, film on.', say: '', text: '',
        art: () => F({ shot: 'MS', mv: 'whip', num: '3', body: person(58, 96, 0.95, { mood: 'worry', shirt: '#4b8bd6', skin: skinC, bottom: 230 }) + clothPad(30, 244, 56, 20, '#fff') + kiosk(108, 80, 60, 130) + timer(90, 296, '00:00:20', { size: 12 }) }) },
      { a: 20, b: 25, shot: 'CU', mv: 'locked', act: 'Timer stops at [real time] as the film sits flush.', say: '', text: 'Machine: done. Team: …',
        art: () => F({ shot: 'CU', mv: 'locked', num: '4', body: phone(44, 66, 92, 176, { film: 'flush', screen: 'lit' }) + timer(90, 272, '[REAL TIME]', { size: 12 }) + sticker(90, 302, 'MACHINE: DONE. TEAM: …', { size: 11 }) }) },
      { a: 25, b: 30, shot: 'MS', mv: 'locked', act: 'The swan collapses.', say: 'STAFF A: “Machine jeet gayi.” (The machine won.)', text: 'Cut for your exact phone. Under 60 seconds.',
        art: () => F({ shot: 'MS', mv: 'locked', num: '5', body: person(90, 100, 1.1, { mood: 'smug', shirt: C.purple, skin: skinB }) + `<path d="M64,244 q4,-20 18,-8 q8,10 22,2 q-4,14 -18,16 q-14,2 -22,-10Z" fill="#fff" stroke="${C.ink}" stroke-width="2"/>` + sticker(90, 296, 'UNDER 60 SECONDS.', { size: 13 }) }) },
    ],
  },
  {
    id: 'S4', title: 'Which Half?', kind: 'COMMENT GAME', len: 12, block: 'TABLE BLOCK', tag: 'CLEAR',
    cast: 'Two staffers', props: 'Dummy with CLEAR film on one half only',
    rule: 'Before rolling, check which half really looks like nothing’s on, and reveal that one. Hold the “LEFT or RIGHT” pause about 2 seconds.',
    plan: { kind: 'table', cams: [{ x: 200, y: 116, ang: 0, label: 'A' }], actors: [{ x: 160, y: 24, label: 'A', col: skinB }, { x: 250, y: 24, label: 'B', col: skinA }], lights: [{ x: 70, y: 70, label: 'TUBE' }, { x: 330, y: 70, label: 'TUBE' }] },
    beats: [
      { a: 0, b: 2, shot: 'MS', mv: 'locked', act: 'Two staffers stare at the dummy.', say: 'A: “Left pe film hai.” B: “Right.”', text: 'One half has our CLEAR film. Which one?',
        art: () => F({ shot: 'MS', mv: 'locked', num: '1', body: person(40, 90, 0.9, { mood: 'flat', shirt: C.pink, skin: skinB, bottom: 210 }) + person(140, 90, 0.9, { mood: 'flat', shirt: C.green, skin: skinA, bottom: 210 }) + phone(64, 150, 52, 100, { film: 'half', screen: 'glossy' }) + sticker(90, 296, 'WHICH ONE?', { size: 14 }) }) },
      { a: 2, b: 6, shot: 'CU', mv: 'tilt', act: 'Slow tilt under the factory lights.', say: 'A: “Left pe chamak hai.” (The left is shiny.) B: “Woh tumhara chehra hai.” (That’s your face.)', text: '',
        art: () => F({ shot: 'CU', mv: 'tilt', num: '2', body: phone(30, 54, 120, 232, { film: 'half', screen: 'glossy' }) + arrow([164, 270, 164, 214], { w: 2.2 }) }) },
      { a: 6, b: 8, shot: 'CU', mv: 'locked', act: 'Hold for two seconds so people can answer.', say: '', text: 'Comment LEFT or RIGHT.',
        art: () => F({ shot: 'CU', mv: 'locked', num: '3', bg: C.Y, body: phone(54, 92, 72, 140, { film: 'half', screen: 'glossy' }) + sticker(90, 60, 'COMMENT', { size: 18, rot: -3 }) + note(40, 262, 'LEFT', { size: 20 }) + note(140, 262, 'RIGHT', { size: 20 }) }) },
      { a: 8, b: 12, shot: 'MACRO', mv: 'locked', act: 'A fingernail lifts the corner on the right half.', say: '', text: 'Right. Virtually invisible. 99%+ light transmittance.',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '4', body: phone(20, 70, 140, 220, { film: 'half', screen: 'glossy' }) + hand(150, 250, 0.8, { rot: -50, skin: skinB }) + circleMark(132, 98, 15) + sticker(90, 304, '99%+ LIGHT TRANSMITTANCE', { size: 10 }) }) },
    ],
  },
  {
    id: 'S5', title: 'Uncle, Not the Kurta', kind: 'SKIT', len: 20, block: 'TABLE BLOCK', tag: 'THE INSTALL',
    cast: 'Uncle, young staffer', props: 'Dummy · dust wipe · microfiber · kiosk · film',
    rule: 'Cast a friend or colleague as the uncle. The kiosk beat is one real take.',
    plan: { kind: 'table', cams: [{ x: 200, y: 116, ang: 0, label: 'A' }, { x: 340, y: 120, ang: 25, label: 'B macro' }], actors: [{ x: 150, y: 24, label: 'UNCLE', col: skinC }, { x: 260, y: 24, label: 'STAFF', col: skinB }], lights: [{ x: 60, y: 70, label: 'KEY' }] },
    beats: [
      { a: 0, b: 3, shot: 'MCU', mv: 'push', act: 'Uncle breathes on the dummy and wipes it on his kurta.', say: '', text: 'Every uncle. Every phone.',
        art: () => F({ shot: 'MCU', mv: 'push', num: '1', body: person(90, 96, 1.15, { mood: 'open', mustache: true, kurta: true, shirt: '#f2efe6', skin: skinC }) + phone(70, 190, 50, 96, { screen: 'glossy' }) + `<ellipse cx="124" cy="150" rx="16" ry="9" fill="#fff" opacity="0.7"/>` + sticker(90, 302, 'EVERY UNCLE. EVERY PHONE.', { size: 11 }) }) },
      { a: 3, b: 6, shot: 'CU', mv: 'locked', act: 'Streaks and lint. Young staffer, horrified.', say: 'STAFF: “Uncle, ye kya kar diya?” (Uncle, what have you done?)', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '2', body: phone(30, 60, 120, 230, { screen: 'glossy', prints: true }) + `<path d="M50,110 q40,-10 80,6 M46,150 q50,-8 90,10" stroke="#fff" stroke-width="3" opacity="0.5" fill="none" stroke-linecap="round"/>` + dust(100, 220, 6, 20) + person(150, 284, 0.55, { mood: 'shock', shirt: C.pink, skin: skinB, bottom: 330 }) }) },
      { a: 6, b: 14, shot: 'MACRO · ASMR', mv: 'locked', act: 'She takes over: dust wipe, slow microfiber circles. Capture clean ASMR audio.', say: '', text: 'One speck of dust = one bubble forever.',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '3', body: phone(30, 66, 120, 226, { screen: 'matte' }) + dust(60, 120, 7, 14) + clothPad(60, 150, 70, 40, '#fff') + curveArrow(70, 218, 90, 240, 130, 214, { w: 2.2 }) + sticker(90, 304, 'ONE SPECK = ONE BUBBLE FOREVER', { size: 9.5 }) }) },
      { a: 14, b: 18, shot: 'MS', mv: 'locked', act: 'Kiosk cut, film on, flush.', say: '', text: '',
        art: () => F({ shot: 'MS', mv: 'locked', num: '4', body: kiosk(18, 60, 70, 140) + phone(104, 100, 56, 108, { film: 'flush', screen: 'lit' }) + sparkle(132, 70, 10, C.Y, C.ink) }) },
      { a: 18, b: 20, shot: 'MS', mv: 'locked', act: 'Uncle reaches for his kurta again; she pulls the phone away.', say: 'STAFF: “Kurta pehnne ke liye hai, uncle.” (The kurta is for wearing.)', text: 'Wipe. Cut. Done.',
        art: () => F({ shot: 'MS', mv: 'locked', num: '5', body: person(46, 106, 0.95, { mood: 'worry', mustache: true, kurta: true, shirt: '#f2efe6', skin: skinC }) + person(138, 130, 0.95, { mood: 'smug', shirt: C.pink, skin: skinB }) + phone(110, 200, 44, 84, { film: 'flush', screen: 'lit', rot: -14 }) + sticker(90, 302, 'WIPE. CUT. DONE.', { size: 13 }) }) },
    ],
  },
  {
    id: 'S6', title: 'Your Phone Is Not a Mirror', kind: 'SKIT', len: 15, block: 'TABLE BLOCK', tag: 'MATTE',
    cast: 'A girl, a friend', props: 'Glossy dummy · MATTE film · kiosk',
    rule: 'Lock the camera between the glossy shot and the MATTE shot, so the film is the only thing that changes.',
    plan: { kind: 'table', cams: [{ x: 200, y: 116, ang: 0, label: 'A LOCKED' }], actors: [{ x: 170, y: 22, label: 'GIRL', col: skinB }, { x: 240, y: 22, label: 'FRIEND', col: skinA }], lights: [{ x: 60, y: 60, label: 'TUBE' }, { x: 340, y: 60, label: 'TUBE' }] },
    beats: [
      { a: 0, b: 3, shot: 'MCU', mv: 'locked', act: 'A girl fixes her hair using the glossy dummy as a mirror under the tube lights.', say: '', text: 'If your phone is also your mirror…',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '1', body: person(90, 112, 1.2, { mood: 'smile', longHair: true, shirt: C.purple, skin: skinB }) + phone(66, 150, 48, 92, { screen: 'glossy' }) + sticker(90, 296, 'IF YOUR PHONE IS ALSO YOUR MIRROR…', { size: 9.5 }) }) },
      { a: 3, b: 7, shot: 'CU', mv: 'locked', act: 'Close-up: thumbprints and glare.', say: 'FRIEND: “Screen dekh rahi ho ya khud ko?” (Looking at the screen or at yourself?)', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '2', body: phone(30, 56, 120, 232, { screen: 'glossy', prints: true }) + sun(150, 56, 11) }) },
      { a: 7, b: 12, shot: 'CU', mv: 'locked', act: 'Kiosk cuts MATTE and it goes on. Same angle, same lights: glare softened, prints hidden.', say: '', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '3', body: phone(30, 56, 120, 232, { screen: 'matte', film: 'flush' }) + sparkle(150, 62, 10, C.Y, C.ink) + sticker(90, 304, 'MATTE GOES ON', { size: 12 }) }) },
      { a: 12, b: 15, shot: 'MCU', mv: 'locked', act: 'She tries the mirror trick again. Nothing. Shrugs.', say: '', text: 'MATTE. Less glare. Fewer prints.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '4', body: person(90, 112, 1.2, { mood: 'flat', longHair: true, shirt: C.purple, skin: skinB }) + phone(66, 150, 48, 92, { screen: 'matte', film: 'flush' }) + sticker(90, 296, 'MATTE. LESS GLARE. FEWER PRINTS.', { size: 9.5 }) }) },
    ],
  },
  {
    id: 'S7', title: '“Glass Wala Do”', kind: 'MYTH BUST', len: 20, block: 'TABLE BLOCK', tag: 'TUFF',
    cast: 'Customer, staffer', props: 'TUFF film · dummy · kiosk',
    rule: 'Impact talk stays with TUFF. Never “unbreakable”, never “scratch-proof”. Spec text is exactly: 0.25–0.35 mm · 4H–5H · EPU layer.',
    plan: { kind: 'table', cams: [{ x: 200, y: 116, ang: 0, label: 'A' }, { x: 330, y: 110, ang: 20, label: 'B macro' }], actors: [{ x: 160, y: 22, label: 'CUST', col: skinA }, { x: 250, y: 22, label: 'STAFF', col: skinB }], lights: [{ x: 70, y: 70, label: 'KEY' }] },
    beats: [
      { a: 0, b: 3, shot: 'MCU 2-shot', mv: 'locked', act: 'Customer asks for glass. Staffer stares into the camera.', say: 'CUST: “Bhai, glass wala do. Strong hota hai.” (Give me the glass one. It’s strong.)', text: 'Is it glass? No. Here’s why that’s good.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '1', body: person(44, 98, 1.0, { mood: 'smug', shirt: C.green, skin: skinA }) + person(140, 98, 1.0, { mood: 'flat', glasses: true, shirt: C.Y, skin: skinB }) + sticker(90, 290, 'IS IT GLASS? NO.', { size: 15 }) }) },
      { a: 3, b: 10, shot: 'MS hands', mv: 'locked', act: 'Staffer bends TUFF into a curve and lets it spring back.', say: 'STAFF: “Glass bulky hota hai, crack hota hai, curve pe baithta hi nahi.” (Bulky, cracks, won’t sit on a curve.)', text: '',
        art: () => F({ shot: 'MS', mv: 'locked', num: '2', body: hand(34, 168, 0.95, { rot: 90, skin: skinB }) + hand(146, 168, 0.95, { rot: -90, skin: skinB, flip: true }) + `<path d="M50,168 Q90,120 130,168" fill="none" stroke="${C.ink}" stroke-width="9" stroke-linecap="round"/><path d="M50,168 Q90,120 130,168" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round"/>` + sticker(90, 262, 'BENDS. SPRINGS BACK.', { size: 12 }) }) },
      { a: 10, b: 16, shot: 'MACRO', mv: 'pan', act: 'TUFF goes on the dummy; macro along the curved edge.', say: '', text: 'TUFF · 0.25–0.35 mm · 4H–5H · EPU layer spreads the hit.',
        art: () => F({ shot: 'MACRO', mv: 'pan', num: '3', body: phone(18, 50, 144, 230, { film: 'flush', screen: 'matte' }) + sticker(90, 296, 'TUFF · 0.25–0.35 MM · 4H–5H', { size: 10 }) }) },
      { a: 16, b: 20, shot: 'MCU', mv: 'locked', act: 'Customer taps it, nods.', say: 'CUST: “Theek hai. Glass nahi chahiye.” (Okay. Don’t need glass.)', text: 'Is it glass? No. That’s the point.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '4', body: person(90, 100, 1.2, { mood: 'smile', shirt: C.green, skin: skinA }) + phone(94, 190, 52, 98, { film: 'flush', screen: 'lit' }) + hand(80, 250, 0.7, { rot: 20, skin: skinA }) + sticker(90, 304, 'THAT’S THE POINT.', { size: 13 }) + crown(122, 36, 0.8) }) },
    ],
  },
  {
    id: 'S8', title: 'Not Your Screen, Uncle', kind: 'SKIT', len: 20, block: 'WINDOW BLOCK', tag: 'PRIVACY',
    cast: 'Staffer, nosy uncle', props: 'Dummy · PRIVACY film sheet · a window',
    rule: 'Going dark at an angle is the film doing it for real. Never fake it in the edit. Shoot last: needs daylight and the window.',
    plan: { kind: 'window', cams: [{ x: 120, y: 116, ang: -8, label: 'A' }, { x: 300, y: 116, ang: 8, label: 'B' }], actors: [{ x: 190, y: 90, label: 'STAFF', col: skinB }, { x: 230, y: 90, label: 'UNCLE', col: skinC }], lights: [] },
    beats: [
      { a: 0, b: 3, shot: 'MS', mv: 'locked', act: 'Staffer on a bench with the dummy. Uncle slides closer, neck stretching.', say: '', text: 'There’s always one.',
        art: () => F({ shot: 'MS', mv: 'locked', num: '1', body: person(54, 126, 0.9, { mood: 'flat', shirt: C.pink, skin: skinB, bottom: 240 }) + phone(40, 190, 40, 76, { screen: 'lit' }) + `<g transform="rotate(-14 130 130)">${person(130, 126, 0.9, { mood: 'open', mustache: true, kurta: true, shirt: '#f2efe6', skin: skinC, bottom: 260 })}</g>` + sticker(90, 296, 'THERE’S ALWAYS ONE.', { size: 13 }) }) },
      { a: 3, b: 8, shot: 'MS', mv: 'locked', act: 'Every time the staffer scoots away, uncle follows. Pure comedy.', say: '', text: '',
        art: () => F({ shot: 'MS', mv: 'locked', num: '2', body: person(40, 126, 0.85, { mood: 'worry', shirt: C.pink, skin: skinB, bottom: 240 }) + person(112, 126, 0.85, { mood: 'open', mustache: true, kurta: true, shirt: '#f2efe6', skin: skinC, bottom: 260 }) + arrow([60, 270, 24, 270], { w: 2.4 }) + arrow([130, 270, 94, 270], { w: 2.4, col: C.amber }) + note(90, 304, 'scoot… follow…', { size: 12 }) }) },
      { a: 8, b: 15, shot: 'MS → CU', mv: 'tilt', act: 'Staffer holds a PRIVACY sheet up to the window: see-through face-on, dark when tilted. Uncle tries every angle, even crouching.', say: 'STAFF: “Saamne se sab. Side se kuch nahi.” (Everything from the front. Nothing from the side.)', text: '',
        art: () => F({ shot: 'MS', mv: 'tilt', num: '3', bg: '#bfeaff', body: `<rect x="14" y="40" width="152" height="150" fill="#fff" stroke="${C.ink}" stroke-width="3" opacity="0.9"/><line x1="90" y1="40" x2="90" y2="190" stroke="${C.ink}" stroke-width="2"/><rect x="26" y="206" width="52" height="70" rx="4" fill="#bfeaff" stroke="${C.ink}" stroke-width="2.4"/><path d="M104,206 L154,222 L154,288 L104,272Z" fill="#14161a" stroke="${C.ink}" stroke-width="2.4"/>` + note(52, 296, 'FRONT', { size: 11 }) + note(130, 304, '35°+', { size: 11 }) }) },
      { a: 15, b: 20, shot: 'MCU', mv: 'locked', act: 'Uncle, defeated, pretends to check the time.', say: '', text: 'PRIVACY. Blocks side views at 35°. Not your screen. Not your business.',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '4', body: person(90, 104, 1.2, { mood: 'flat', mustache: true, kurta: true, shirt: '#f2efe6', skin: skinC }) + `<circle cx="146" cy="214" r="12" fill="#fff" stroke="${C.ink}" stroke-width="2.4"/><path d="M146,214 L146,206 M146,214 L152,217" stroke="${C.ink}" stroke-width="2"/>` + sticker(90, 300, 'NOT YOUR SCREEN. NOT YOUR BUSINESS.', { size: 9 }) }) },
    ],
  },
  {
    id: 'S9', title: 'Types of Customers', kind: 'ONE ACTOR, FOUR CHARACTERS', len: 30, block: 'MACHINE BLOCK', tag: 'THE MACHINE',
    cast: 'One actor playing four people', props: 'Dummy · TUFF film · kiosk · microfiber',
    rule: 'Costume changes by one prop each (cap, specs, scarf, towel) so the four read at a glance. Beat timings after 0–2s are PROPOSED (the deck gives order, not seconds).',
    plan: { kind: 'machine', cams: [{ x: 200, y: 116, ang: 0, label: 'A' }], actors: [{ x: 200, y: 78, label: 'ACTOR', col: skinA }], lights: [{ x: 70, y: 90, label: 'KEY' }, { x: 330, y: 90, label: 'FILL' }] },
    beats: [
      { a: 0, b: 2, shot: 'TITLE', mv: 'locked', act: 'Title card.', say: '', text: 'Types of people at a screen protector shop.',
        art: () => frame({ bg: C.Y, shot: 'TITLE', mv: 'locked', num: '1', body: note(90, 120, 'TYPES OF PEOPLE', { size: 20, rot: -3 }) + note(90, 156, 'AT A SCREEN', { size: 20, rot: -3 }) + note(90, 192, 'PROTECTOR SHOP', { size: 20, rot: -3 }) + crown(78, 232, 1) + smiley(40, 276, 12) }) },
      { a: 2, b: 8, shot: 'MCU', mv: 'push', act: 'THE WORRIER. The kiosk screen finds the model.', say: '“Fit aayega na? Pakka? Qasam khao.” (It’ll fit? Promise? Swear on it.)', text: 'Will it fit? Yes.',
        art: () => F({ shot: 'MCU', mv: 'push', num: '2', body: person(90, 96, 1.2, { mood: 'worry', shirt: C.pink, skin: skinA, hat: null }) + `<rect x="30" y="206" width="120" height="58" rx="6" fill="#dfe6ee" stroke="${C.ink}" stroke-width="2"/><rect x="40" y="218" width="80" height="8" rx="3" fill="#8a96a6"/><rect x="40" y="234" width="60" height="8" rx="3" fill="${C.Y}"/>` + sticker(90, 296, 'WILL IT FIT? YES.', { size: 13 }) }) },
      { a: 8, b: 13, shot: 'MCU → CU', mv: 'locked', act: 'THE GLASS GUY. Cut to the TUFF bend.', say: '“Glass wala nahi hai?” (No glass one?)', text: '',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '3', body: person(90, 96, 1.2, { mood: 'smug', glasses: true, shirt: C.green, skin: skinA }) + `<path d="M46,268 Q90,224 134,268" fill="none" stroke="${C.ink}" stroke-width="9" stroke-linecap="round"/><path d="M46,268 Q90,224 134,268" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round"/>` }) },
      { a: 13, b: 19, shot: 'MCU', mv: 'locked', act: 'THE SPEEDRUNNER. Cut to the timer on the cut.', say: '“Bhai jaldi, rickshaw wait kar raha hai.” (Hurry, my rickshaw’s waiting.)', text: '',
        art: () => F({ shot: 'MCU', mv: 'whip', num: '4', body: person(90, 96, 1.2, { mood: 'open', hat: C.ink, shirt: '#4b8bd6', skin: skinA }) + timer(90, 232, '00:00:41', { size: 15 }) + arrow([128, 200, 156, 200], { w: 2.4 }) }) },
      { a: 19, b: 25, shot: 'MCU', mv: 'locked', act: 'THE OVER-CLEANER. Wipes the screen 14 times. Staffer cuts in.', say: '“Bas bhai, baaki machine ka kaam hai.” (Enough, the machine does the rest.)', text: '',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '5', body: person(90, 96, 1.2, { mood: 'shock', shirt: C.purple, skin: skinA }) + phone(62, 190, 56, 98, { screen: 'matte' }) + clothPad(68, 214, 44, 26, '#fff') + sticker(144, 196, '×14', { size: 15, rot: 6 }) }) },
      { a: 25, b: 30, shot: 'SPLIT 2×2', mv: 'locked', act: 'Split screen: all four admire their phones in sync.', say: '', text: 'Every type. One machine. Exact fit. Which one are you?',
        art: () => F({ shot: 'SPLIT', mv: 'locked', num: '6', body: `<line x1="90" y1="40" x2="90" y2="260" stroke="${C.ink}" stroke-width="3"/><line x1="0" y1="150" x2="180" y2="150" stroke="${C.ink}" stroke-width="3"/>` + [[45, 98, C.pink], [135, 98, C.green], [45, 208, '#4b8bd6'], [135, 208, C.purple]].map(([x, y, c]) => person(x, y - 14, 0.55, { mood: 'smile', shirt: c, skin: skinA, bottom: y + 40 }) + phone(x - 10, y + 6, 20, 38, { film: 'flush', screen: 'lit' })).join('') + sticker(90, 296, 'WHICH ONE ARE YOU?', { size: 13 }) }) },
    ],
  },
  {
    id: 'S10', title: 'POV: I’m the Film', kind: 'VOICEOVER', len: 30, block: 'MACHINE BLOCK', tag: 'THE MACHINE',
    cast: 'Voiceover + hands', props: 'Blank film sheet · kiosk · dummy · dust wipe · microfiber',
    rule: 'Deadpan voiceover, no music bed under it. Record the VO after picture lock so the timings land. Shoot the macros on the same pass as S2.',
    plan: { kind: 'machine', cams: [{ x: 160, y: 116, ang: 0, label: 'A macro' }, { x: 260, y: 116, ang: 0, label: 'B WS' }], actors: [{ x: 200, y: 62, label: 'HANDS', col: skinB }], lights: [{ x: 70, y: 90, label: 'KEY' }, { x: 330, y: 90, label: 'RAKE' }] },
    beats: [
      { a: 0, b: 3, shot: 'MACRO', mv: 'locked', act: 'Macro on a blank sheet in the machine.', say: 'VO: “I was a blank sheet. No phone. No purpose.”', text: '',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '1', body: filmSheet(26, 70, 128, 180, {}) + note(90, 286, 'blank.', { size: 16 }) }) },
      { a: 3, b: 8, shot: 'CU screen', mv: 'locked', act: 'A model gets picked on the screen.', say: 'VO: “Then someone typed in their phone. Suddenly I had a shape.”', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '2', body: `<rect x="16" y="64" width="148" height="190" rx="8" fill="#dfe6ee" stroke="${C.ink}" stroke-width="3"/>` + [0, 1, 2, 3, 4].map((i) => `<rect x="30" y="${84 + i * 32}" width="${96 - (i % 2) * 20}" height="14" rx="4" fill="${i === 2 ? C.Y : '#8a96a6'}" stroke="${i === 2 ? C.ink : 'none'}" stroke-width="2"/>`).join('') + hand(150, 214, 0.7, { rot: -30, skin: skinB }) }) },
      { a: 8, b: 12, shot: 'MACRO', mv: 'locked', act: 'Blade macro.', say: 'VO: “That tickled.”', text: '',
        art: () => F({ shot: 'MACRO', mv: 'locked', num: '3', body: filmSheet(26, 80, 128, 170, {}) + `<path d="M40,150 q50,-24 100,0 q-6,36 -50,40 q-44,-4 -50,-40Z" fill="none" stroke="#ff5a4d" stroke-width="2.4" stroke-dasharray="5 4"/>` + blade(150, 126, 30, 200) }) },
      { a: 12, b: 17, shot: 'CU slow-mo', mv: 'locked', act: 'Slow-mo backing peel.', say: 'VO: “They peeled my backing. Rude. But fair.”', text: '',
        art: () => F({ shot: 'CU · 120 FPS', mv: 'locked', num: '4', body: filmSheet(30, 90, 118, 170, {}) + `<path d="M30,90 q-18,26 30,40 q40,-8 20,-40Z" fill="#fff" opacity="0.85" stroke="${C.ink}" stroke-width="2"/>` + hand(34, 96, 0.8, { rot: -40, skin: skinB }) + sticker(90, 300, 'SLOW-MO', { size: 12 }) }) },
      { a: 17, b: 22, shot: 'MCU', mv: 'locked', act: 'Wipe and microfiber on the dummy.', say: 'VO: “They cleaned the house before I moved in. Respect.”', text: '',
        art: () => F({ shot: 'MCU', mv: 'locked', num: '5', body: phone(40, 70, 100, 190, { screen: 'matte' }) + clothPad(56, 130, 68, 38, '#fff') + dust(80, 100, 6, 22) + curveArrow(60, 200, 90, 224, 126, 196, { w: 2.2 }) }) },
      { a: 22, b: 27, shot: 'CU', mv: 'locked', act: 'The film lands, smoothed.', say: 'VO: “Edge to edge. Perfect camera hole. I fit exactly one phone in the world.”', text: '',
        art: () => F({ shot: 'CU', mv: 'locked', num: '6', body: phone(30, 56, 120, 232, { film: 'flush', screen: 'lit' }) + sparkle(150, 70, 11, C.Y, C.ink) }) },
      { a: 27, b: 30, shot: 'END CARD', mv: 'locked', act: 'End card.', say: 'VO: “Yours.”', text: 'Cut for your exact phone.',
        art: () => frame({ bg: C.Y, shot: 'END', mv: 'locked', num: '7', body: note(90, 150, 'YOURS.', { size: 38, rot: -4 }) + crown(76, 188, 1.1) + sticker(90, 270, 'CUT FOR YOUR EXACT PHONE.', { size: 11 }) + smiley(150, 56, 12) }) },
    ],
  },
];

export const RUNSHEET = [
  { blk: 'MACHINE BLOCK', c: C.Y, items: [['S1', 'Bilkul Fit Hai', 25], ['S2', 'The Bubble Roommate', 25], ['S3', '60 Seconds, Go', 30], ['S9', 'Types of Customers', 30], ['S10', 'POV: I’m the Film', 30]], note: 'They share the cut footage, so keep rolling on every cut.' },
  { blk: 'TABLE BLOCK', c: C.Y2, items: [['S4', 'Which Half?', 12], ['S5', 'Uncle, Not the Kurta', 20], ['S6', 'Your Phone Is Not a Mirror', 15], ['S7', '“Glass Wala Do”', 20]], note: 'Under the lights. Lock the camera for S6.' },
  { blk: 'WINDOW BLOCK', c: '#bfeaff', items: [['S8', 'Not Your Screen, Uncle', 20]], note: 'Last, with daylight.' },
];
export { floorPlan };
